# Generated by Django 5.1.6 on 2025-03-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='email',
        ),
    ]
