# Generated by Django 5.1.6 on 2025-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='barber_profiles/')),
                ('shop_name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('professional_email', models.EmailField(max_length=254, unique=True)),
                ('shop_banner', models.ImageField(blank=True, null=True, upload_to='shop_banners/')),
                ('available_time_slots', models.CharField(help_text='Example: 10:00 AM - 4:00 PM', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
