# Generated by Django 5.1.6 on 2025-03-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0005_alter_barberprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberprofile',
            name='professional_email',
        ),
    ]
